# generated by datamodel-codegen:
#   filename:  https://api.koulis.ai/openapi.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field


class CreateRestaurantInput(BaseModel):
    name: Annotated[
        str, Field(examples=["Le Bouillon Chartier"], max_length=200, min_length=1)
    ]
    slug: Annotated[str | None, Field(max_length=200, min_length=1)] = None
    address: Annotated[
        str | None, Field(examples=["7 Rue du Faubourg Montmartre"], max_length=300)
    ] = None
    postal_code: Annotated[str | None, Field(examples=["75009"], max_length=20)] = None
    city_name: Annotated[str | None, Field(examples=["Paris"], max_length=100)] = None
    country_code: Annotated[
        str | None, Field(examples=["FR"], max_length=2, min_length=2)
    ] = "FR"
    latitude: Annotated[float | None, Field(examples=[48.8718])] = None
    longitude: Annotated[float | None, Field(examples=[2.3448])] = None
    phone: Annotated[str | None, Field(examples=["+33147708629"], max_length=20)] = None
    actor_type: Annotated[str | None, Field(examples=["restaurant"], max_length=50)] = (
        None
    )
    """
    Type d'établissement : restaurant, café, bar, etc.
    """
    price_range: Annotated[int | None, Field(examples=[2], ge=1, le=4)] = None
    """
    Échelle de prix de 1 (€) à 4 (€€€€)
    """
    excerpt: Annotated[str | None, Field(max_length=200)] = None
    rating: Annotated[float | None, Field(examples=[4.2], ge=0.0, le=5.0)] = None
    cuisines: Annotated[
        list[str] | None, Field(examples=[["française", "bistrot"]])
    ] = []
    formats: Annotated[list[str] | None, Field(examples=[["brunch", "déjeuner"]])] = []
    dietary: Annotated[list[str] | None, Field(examples=[["végétarien"]])] = []
    atmosphere: list[str] | None = []
    services: list[str] | None = []
    is_published: bool | None = False
    """
    Indique si le restaurant est visible publiquement
    """
    source: Annotated[str | None, Field(examples=["lakreme"], max_length=30)] = "api"
    """
    Origine de la donnée : lakreme, sdk, manual, etc.
    """


class ErrorResponse(BaseModel):
    message: Annotated[str, Field(examples=["Restaurant not found"])]


class UpsertAvailabilitiesResponse(BaseModel):
    restaurant_id: Annotated[
        UUID, Field(examples=["b47d4e2a-1c3f-4a7e-9b2d-5f6a8c3e1d0b"])
    ]
    day: Annotated[str, Field(examples=["2026-05-12"])]
    slots_written: Annotated[int, Field(examples=[5])]


class Slot(BaseModel):
    slot_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T19:30:00Z"])]
    """
    ISO 8601 datetime with explicit timezone offset (Z or ±HH:MM). Naive datetimes (no offset) are rejected.
    """
    capacity_total: Annotated[int, Field(examples=[10], ge=1, le=500)]


class UpsertAvailabilitiesInput(BaseModel):
    day: Annotated[str, Field(examples=["2026-05-12"])]
    slots: list[Slot]


class Query(BaseModel):
    datetime: Annotated[str, Field(examples=["2026-05-12T20:00:00.000Z"])]
    party_size: Annotated[int, Field(examples=[2])]
    window_hours: Annotated[int, Field(examples=[2])]


class AvailabilitySlot(BaseModel):
    id: Annotated[UUID, Field(examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])]
    restaurant_id: Annotated[
        UUID, Field(examples=["b47d4e2a-1c3f-4a7e-9b2d-5f6a8c3e1d0b"])
    ]
    slot_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T20:00:00.000Z"])]
    capacity_total: Annotated[int, Field(examples=[10])]
    capacity_remaining: Annotated[int, Field(examples=[6])]


class HoldResponse(BaseModel):
    hold_id: Annotated[UUID, Field(examples=["d4e5f6a7-b8c9-0123-4567-890abcdef012"])]
    restaurant_id: Annotated[
        UUID, Field(examples=["b47d4e2a-1c3f-4a7e-9b2d-5f6a8c3e1d0b"])
    ]
    restaurant_name: Annotated[str, Field(examples=["Le Bouillon Chartier"])]
    slot_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T20:00:00.000Z"])]
    party_size: Annotated[int, Field(examples=[2])]
    expires_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T20:05:00.000Z"])]
    expires_in_seconds: Annotated[int, Field(examples=[300])]


class CreateHoldInput(BaseModel):
    restaurant_id: Annotated[
        UUID, Field(examples=["b47d4e2a-1c3f-4a7e-9b2d-5f6a8c3e1d0b"])
    ]
    slot_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T19:30:00Z"])]
    """
    ISO 8601 datetime with explicit timezone offset (Z or ±HH:MM). Naive datetimes (no offset) are rejected.
    """
    party_size: Annotated[int, Field(examples=[2], ge=1, le=20)]


class Status(StrEnum):
    confirmed = "confirmed"


class ReservationResponse(BaseModel):
    status: Status
    idempotent_replay: Annotated[bool, Field(examples=[False])]
    confirmation_id: Annotated[
        UUID, Field(examples=["f1e2d3c4-b5a6-7890-1234-567890abcdef"])
    ]
    restaurant_id: Annotated[
        UUID, Field(examples=["b47d4e2a-1c3f-4a7e-9b2d-5f6a8c3e1d0b"])
    ]
    restaurant_name: Annotated[str, Field(examples=["Le Bouillon Chartier"])]
    slot_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T20:00:00.000Z"])]
    party_size: Annotated[int, Field(examples=[2])]
    customer_name: Annotated[str, Field(examples=["Marie Dupont"])]
    customer_phone: Annotated[str, Field(examples=["+33600000000"])]
    customer_email: Annotated[str, Field(examples=["client@example.com"])]
    special_requests: Annotated[str, Field(examples=["Table en terrasse"])]
    created_at: Annotated[str, Field(examples=["2026-05-12T20:01:00.000Z"])]


class CreateReservationInput(BaseModel):
    hold_id: Annotated[UUID, Field(examples=["d4e5f6a7-b8c9-0123-4567-890abcdef012"])]
    customer_name: Annotated[
        str, Field(examples=["Marie Dupont"], max_length=200, min_length=1)
    ]
    customer_phone: Annotated[
        str, Field(examples=["+33600000000"], max_length=30, min_length=6)
    ]
    customer_email: Annotated[
        EmailStr, Field(examples=["client@example.com"], max_length=200)
    ]
    special_requests: Annotated[
        str | None, Field(examples=["Table en terrasse"], max_length=2000)
    ] = None


class ConsumeSlotInput(BaseModel):
    slot_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T19:30:00Z"])]
    """
    ISO 8601 datetime with explicit timezone offset (Z or ±HH:MM). Naive datetimes (no offset) are rejected.
    """
    party_size: Annotated[int, Field(examples=[2], ge=1, le=20)]


class RestoreSlotInput(BaseModel):
    slot_at: Annotated[AwareDatetime, Field(examples=["2026-05-12T19:30:00Z"])]
    """
    ISO 8601 datetime with explicit timezone offset (Z or ±HH:MM). Naive datetimes (no offset) are rejected.
    """
    party_size: Annotated[int, Field(examples=[2], ge=1, le=20)]


class RegisterWebhookOutput(BaseModel):
    id: Annotated[UUID, Field(examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])]
    url: Annotated[str, Field(examples=["https://example.com/webhooks/koulis"])]
    events_subscribed: Annotated[list[str], Field(examples=[["reservation.created"]])]
    description: Annotated[str, Field(examples=["Main webhook"])]
    is_active: Annotated[bool, Field(examples=[True])]
    secret: Annotated[
        str,
        Field(
            examples=[
                "a3f2b1c4d5e6f7890123456789abcdef0123456789abcdef0123456789abcdef"
            ]
        ),
    ]
    """
    HMAC secret — shown only on creation, store it safely
    """
    created_at: Annotated[str, Field(examples=["2026-05-11T14:00:00.000Z"])]


class Event(StrEnum):
    reservation_created = "reservation.created"
    hold_created = "hold.created"
    hold_released = "hold.released"
    hold_expired = "hold.expired"


class RegisterWebhookInput(BaseModel):
    url: Annotated[AnyUrl, Field(examples=["https://example.com/webhooks/koulis"])]
    events: Annotated[
        list[Event],
        Field(
            examples=[
                ["reservation.created", "hold.created", "hold.released", "hold.expired"]
            ],
            min_length=1,
        ),
    ]
    """
    Events that this endpoint will be notified for. Available events:
    - reservation.created — A reservation has been confirmed.
    - hold.created — A hold has been created on a slot (capacity temporarily reserved).
    - hold.released — A hold has been converted into a confirmed reservation. Sent immediately before reservation.created for the same hold.
    - hold.expired — A hold has expired without confirmation (capacity restored).
    """
    description: Annotated[
        str | None, Field(examples=["Main webhook"], max_length=200)
    ] = None


class WebhookEndpoint(BaseModel):
    id: Annotated[UUID, Field(examples=["a1b2c3d4-e5f6-7890-abcd-ef1234567890"])]
    url: Annotated[str, Field(examples=["https://example.com/webhooks/koulis"])]
    events_subscribed: Annotated[list[str], Field(examples=[["reservation.created"]])]
    description: Annotated[str, Field(examples=["Main webhook"])]
    is_active: Annotated[bool, Field(examples=[True])]
    created_at: Annotated[str, Field(examples=["2026-05-11T14:00:00.000Z"])]


class WebhookDelivery(BaseModel):
    id: UUID
    endpoint_id: UUID
    event_type: Annotated[str, Field(examples=["reservation.created"])]
    event_id: Annotated[str, Field(examples=["evt_abc123def456"])]
    status: Annotated[str, Field(examples=["pending"])]
    attempts: Annotated[int, Field(examples=[0])]
    next_attempt_at: Annotated[str, Field(examples=["2026-05-11T14:00:05.000Z"])]
    last_attempt_at: Annotated[str, Field(examples=[None])]
    last_response_status: Annotated[int, Field(examples=[None])]
    created_at: Annotated[str, Field(examples=["2026-05-11T14:00:00.000Z"])]


class Restaurant(CreateRestaurantInput):
    id: Annotated[UUID, Field(examples=["b47d4e2a-1c3f-4a7e-9b2d-5f6a8c3e1d0b"])]
    reviews_count: Annotated[int, Field(examples=[128])]
    created_at: Annotated[str, Field(examples=["2026-01-15T10:30:00.000Z"])]
    updated_at: Annotated[str, Field(examples=["2026-01-15T10:30:00.000Z"])]


class RestaurantWithSlots(Restaurant):
    available_slots: list[str]


class AvailabilitiesResponse(BaseModel):
    restaurant_id: Annotated[
        UUID, Field(examples=["b47d4e2a-1c3f-4a7e-9b2d-5f6a8c3e1d0b"])
    ]
    restaurant_name: Annotated[str, Field(examples=["Le Bouillon Chartier"])]
    query: Query
    count: Annotated[int, Field(examples=[4])]
    slots: list[AvailabilitySlot]


class ListWebhooksResponse(BaseModel):
    count: Annotated[int, Field(examples=[1])]
    results: list[WebhookEndpoint]


class ListWebhookDeliveriesResponse(BaseModel):
    count: Annotated[int, Field(examples=[1])]
    results: list[WebhookDelivery]


class SearchResponse(BaseModel):
    count: Annotated[int, Field(examples=[3])]
    results: list[RestaurantWithSlots]
